### ISSUE TITLE
k.range functionality

### ISSUE THREAD

**Issue by hamidyou** [dhershman1/kyanite#25]
**Function in Question**

Which Function(s) (if any) is in question?  Range

**What it is Currently**

What is the documentation you want to change currently?  Second parameter currently represents the final number +1. 

**What you expect/want to see**

I think that the second parameter or when single it should be the highest number you want.  Maybe?

**Comment by dhershman1** [comment]
The idea behind it is to create a range from point A to B and the numbers to get there, so the range from 1 to 10 is `[1, 2, 3, 4, 5, 6, 7, 8, 9]` 10 is not within its own range since that exceeds the range.

However I will leave this open because it may be worth talking about and mixing up the formula a little bit...

**Comment by hamidyou** [comment]
got it.  would it be possible to create one that is inclusive (rangeIn) and one that is exclusive (rangeEx)?

**Comment by dhershman1** [comment]
In the state of `range` the parameter `from` is inclusive and the parameter `to` is exclusive you COULD make the value inclusive by doing something like:

```js
const valTo = 5

K.range(1, valTo + 1) // => [1, 2, 3, 4, 5]
```

**Comment by dhershman1** [comment]
I think it is a good idea to leave range alone with it's return. Since this can also be addressed with adding 1 onto the `to` param
