### ISSUE TITLE
includes in VSCode

### ISSUE THREAD

**Issue by hamidyou** [dhershman1/kyanite#27]
**Function in Question**

includes()

**What it is Currently**

The information that comes up when using it in VSCode.  See attachment

**What you expect/want to see**

(value: any, list: array) => boolean

**Comment by dhershman1** [comment]
What currently outputs from includes is technically correct.

`const includes: (a: any, list: any[]) => boolean`

since the list that is passed in needs to be an array `[]` and the values of the array could technically be anything, which means `any[]` does make sense.

However I will look into changing the param `a` to `value` to hopefully clear up confusion within the docs too.

**Comment by dhershman1** [comment]
This is a typescript issue since typescript doesn't do well when inferring or defining functional stuff. The fix for that is out of my hands for now.
