### ISSUE TITLE
sample Proposal

### ISSUE THREAD

**Issue by hamidyou** [dhershman1/kyanite#57]
## sample

**Signature(s):**
`Number a -> Number b -> Number c`

**Type:** `Array` . 

**Leave a description of the purpose of your function here** 

Pull a random item from an array

### Why

**Why are you suggesting this new function?**
Simplifies the process of creating random numbers with varying ranges

### Syntax

**Parameters:**
`arr` - `Array`: The array to pull from

```js
K.sample(arr)
```

### Usage

```js
K.sample(['pony', 'unicorn', 'rainbow']) //=> 'unicorn'
```

**Comment by dhershman1** [comment]
There's a lot of things to think about, _technically speaking_ random isn't a pure function, because if you pass it the same arguments it gives you a different result each time.

I guess I'm just not that hardcore though because random might be the only example of "calling the same function twice with the same arguments returns different results" that I don't agree with because it's literally in the name

Other things if you look at the Ramda library which tries to be super duper pure doesn't like the idea of random at all unless it's wrapped in an I/O monad like in Haskell or Elm.

And in other instances like Clojure the starting point is defaulted to 0, so you only supply the ending number. Is this a route to take, or is it really just better to let the user decide on that. I don't have a real strong feeling here just food for thought.

Some thought will need to go into it, I am on board I think random would be useful, so we will see.

**Edit/Additional**: Another route to take may be something like the seed approach, where you generate a seed and if provided with the same seed it returns the same value. A way to retrieve old numbers, which implements a I/O sort of approach which I kind of like, but idk

**MORE Additions**: Or why not even take an approach sort of like how underscores `_.sample` works? `_.sample(['pony', 'unicorn', 'rainbow']) //=> 'unicorn'`

**Comment by hamidyou** [comment]
I get the pure function issue, I didn't think about that.  However, as you said, it is in the name.  Also, couldn't you technically say that given the same parameters, the same thing is always returned?  So, if you are asking between 10 and 20, you will always get a number between 10 and 20.

You also gave me another idea, what if instead of random being a random number based on input, it work like the `_.sample`. It can take in a list type and return a random element from that list.  If someone wants to use it for random numbers, then they can do

`random(range(10,21)) // => a random number between 10 and 20 (inclusive)`

**Comment by dhershman1** [comment]
I think I want to go along with a implementation of this, most likely following the same design as underscores sample

**Comment by dhershman1** [comment]
Sample has been added and is ready for the v0.10.0 release
